#! /bin/sh

GUNICORN=/usr/local/bin/gunicorn
ROOT=/home/box/web/ask/ask
PID=/var/run/gunicorn.pid

APP=ask.wsgi

if [-f $PID]; then rm $PID; fi

cd $ROOT
exec $GUNICORN -c /home/box/web/etc/gunicorn.conf --pid=$PID $APP
